spring:
  application:
    name: EcoChain
  datasource:
    url: jdbc:mysql://MySQL-8.2:3306/ecochain-database
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
#    show-sql: true
  elasticsearch:
    uris: http://localhost:9200
jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_token_expiration: 36000000 # 10 hours
  refresh_token_expiration: 252000000 # 7 days

cloud:
  aws:
    bucket:
      name: ecochain-bucket
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}